apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-app
  labels:
    app: project3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project3-app
  template:
    metadata:
      labels:
        app: project3-app
    spec:
      containers:
      - name: project3-container
        image: 309395755719.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 8081
