apiVersion: v1
kind: Service
metadata:
  name: pandacloud-app
  labels:
    app: pandacloud-app
spec:
  type: LoadBalancer
  selector:
    app: pandacloud-app
  ports:
  - name: http
    port: 80
    targetPort: 8081
